### ISSUE TITLE
Flipped Price Tags in Shop

### ISSUE THREAD

**Issue by DovJacobson** [GamesThatWork/BrushUpBuilds#109]
**Describe the bug**
Lefty users see shop with scene reversed but pricetags noot reversed

**To Reproduce**
1. Be lefthanded
2. Go to shop.'
3. Open any room / theme

**Expected behavior**
Each price tag near its prize

**Screenshots**

<img width="1382" height="851" alt="Image" src="https://github.com/user-attachments/assets/6d64e8fd-88c6-4476-90cd-f92dff33a806" />

**Comment by DovJacobson** [comment]
Fixed as of 1.3.56
please verify

**Comment by tawfik-azzabi** [comment]
The previously reported issue is still reproducible in v1.3.57 on iOS only
When playing as a left-handed user, the price tags are reversed. But after purchasing an item it all resets to the normal state.

**Comment by tawfik-azzabi** [comment]
Still reproductible in v1.3.59

<img width="1400" height="647" alt="Image" src="https://github.com/user-attachments/assets/72590091-296f-426c-b91f-fa18d96c701c" />

**Comment by DovJacobson** [comment]
@tawfik-azzabi you should have label management privilege now.
please remove "please review" tags from issues as they are reviewed

**Comment by DovJacobson** [comment]
please check 1.3.66 on ios and android
(use:  https://bu-pwa.web.app/shop.html to jump to shop with most recent brusher)

if it still fails please answer:

1: Is the Cartoon **SCENE** flipped?  Lefty player sees bathtub on left
2: Is the **PRICE STAR** layout flipped?  Lefty player sees shower 'price star' on left

**Comment by tawfik-azzabi** [comment]
build 1.3.66 tested on Android (Still no access possible on iOS) see screenshot below : 

1 : For lefty players , the Bathtub is on left
2 : For lefty players, the price tags are correctly ajusted with the background (that was not the case untill 1.3.64)

<img width="2877" height="1820" alt="Image" src="https://github.com/user-attachments/assets/8f290f7d-97e0-4681-a6dd-4dbd93005b5b" />

**Comment by tawfik-azzabi** [comment]
Tested again today on iPad and Surface Pro on build v1.3.70 with the same lefty user : 

The price tags are flipped on iPad and correctly Adjusted on Surface Pro : 

iPad : 
<img width="1995" height="1399" alt="Image" src="https://github.com/user-attachments/assets/e9aeb142-927f-4442-b252-9f182c53136e" />


Surface Pro 
<img width="2879" height="1920" alt="Image" src="https://github.com/user-attachments/assets/105d1d8c-8b82-4153-bec3-5d7700319550" />

**Comment by DovJacobson** [comment]
please be sure that this effect is due to iPad vs Windows, not gameplay related

( it seemed like the flipping was visible only at first and then 'fixed itself' after you played with the interface for a while. 
Is that true? )

also this problem is on both iPhone and iPad?

**Comment by tawfik-azzabi** [comment]
When I tested back in v1.3.57, as soon as I buy an item the price tags are sync with the background.
However, in the current build v1.3.70, the tag prices are flipped in iPad for sure and even after a purchase
Note : I still can't test on iPhone as the app is stuck in home page but I'm asking a friend to use his iPhone for test to check both this issue #109 and #121

**Comment by DovJacobson** [comment]
tawfik

I am preparing an override so that you do not need to ask your friend in france for help
i am grateful to your friend and you for this effort - I did not realize how much trouble it was causing.

The override is not simple, so it seems that is not working yet (1..3.73) 

I will update you when it is.





Please use https://bu-pwa.web.app/api/version  to quickly check the latest version.

**Comment by tawfik-azzabi** [comment]
@DovJacobson 

This issue is still occurring in v1.5.032

Lefty users see shop with scene reversed but pricetags not reversed

**Comment by tawfik-azzabi** [comment]
@DovJacobson
- on Windows 11 : the issue is fixed
- on iPhone 15 (iOS26) : This issue is still occurring in v1.5.139 / Lefty users see shop with scene reversed but pricetags not reversed

**Comment by tawfik-azzabi** [comment]
I tested the new build on the iPhone 15, the older iPhone 14 Pro (not easy to borrow for a few minutes 😄), and also on an iPad.
The same behavior is observed on all three devices.

Once the device is rotated to landscape, the background video stabilizes faster than before, at least that’s my perception. That said, from a user-experience perspective, I would still personally prefer the screen to be hard-locked to landscape orientation, as this feels more robust and predictable.

Regarding the inverted background, I can confirm it is the same issue #109 (corrected on Windows) but still occuring on iOS for left-handed users only - the issue is still opened

**Comment by DovJacobson** [comment]
@tawfik-azzabi 
i have changed to ios26 orientation code 
pleaswe test if that cures the problem

**Comment by tawfik-azzabi** [comment]
@DovJacobson : The issue of flipped background is still occurring on iOS 26 v1.5.188 for lefty handed users 

![image](https://github.com/user-attachments/assets/c4a0faf8-bdb6-492c-a32c-ef98756d1752)

**Comment by DovJacobson** [comment]
Thanks* for wrestling with your daughter! *I am* glad the delay was
sufficient even on the slower phone.*
I would also prefer to use screen.orientation.lock() on iOS as we do on
Android.
But it is not supported in most cases.

**Comment by DovJacobson** [comment]
is this an ios only bug?
is it an ios26 only bug?

TIA

**Comment by DovJacobson** [comment]
also important question:

is the background correct for right handed users in ios26?

**Comment by DovJacobson** [comment]
I have gone ahead and attempted to fix blindly. :(
please check for Price Tag Flip on both lefty & righty players in ios26

**Comment by tawfik-azzabi** [comment]
@DovJacobson 
Here’s my observation on iOS 26 – XC222 (I’m waiting for the auth loop fix on XC555 to retest there):
- Left-handed users : the issue still persists - background is inverted on the Store screen (price tag / background flip).
- Right-handed users : no issue observed - background and labels orientation are correct.

So the problem currently appears to be specific to lefty mode on iOS 26, not affecting right-handed users.

**Comment by DovJacobson** [comment]
are you able to check the displayed version number - or does it flash by
too quickly.
please be sure you are updated...
i completey reversed the logic so I expected RIGHTY to fail and LEFTY to
pass.

**Comment by tawfik-azzabi** [comment]
![image](https://github.com/user-attachments/assets/103250ca-70a4-4681-bf1d-46b1ba951d3b)

**Comment by tawfik-azzabi** [comment]
I tested again on v1.5.199 to be sure : 

Profil set up with lefty hand : 

![image](https://github.com/user-attachments/assets/437c69db-abd2-4fe4-862b-424a8453c254)


Screenshot at the shop with the same profile : 

![image](https://github.com/user-attachments/assets/2a59c65e-9dc8-4267-a54c-43f04b05978e)

**Comment by DovJacobson** [comment]
thanks for these screenshots, please let me know the user id (whoami) of this account

**Comment by tawfik-azzabi** [comment]
I'm trying to get in touch with the phone number's holder. Meanwhile here's the profil information, I logged in using a French number 
![image](https://github.com/user-attachments/assets/be64a2cd-6d02-4e6d-886c-98f52f13e551)

**Comment by DovJacobson** [comment]
@tawfik-azzabi i think it is now fixed in the ios case using a sleazy trick

**Comment by tawfik-azzabi** [comment]
@DovJacobson : Quick update regarding the left-handed workaround:

iOS26 (v1.5.204)
Findings are confirmed:
- Left-handed users : background still inverted.
- Right-handed users : orientation and labels are correct.

Android (v1.5.204)
Observations are now, not in a good way, aligned with iOS behavior (left-handed background inverted, right-handed OK).
However, my Android tablet is currently blocked on the app, so these results will need to be revalidated once I regain access.

Windows (v1.5.204)
Orientation and background are correct for both left-handed and right-handed users.

At this stage, the issue is confirmed on iOS, likely present on Android but pending reconfirmation, and not reproducible on Windows, which behaves as expected for both profiles.

**Comment by jcorack2** [comment]
I can confirm that as of the time of this comment, (android 15, version 1.5.215)  the shop tags are still flipped for left-handed brushers.

**Comment by jcorack2** [comment]
Note from developer meeting on 1/8/26 - shop will be 'right handed' for all BU brushers regardless of handedness.

**Comment by DovJacobson** [comment]
i just turned off flipping

**Comment by jcorack2** [comment]
Price tags are still flipped for me as a LH brusher. 
- android 15, chrome browser, v1.5.263

I was still able to purchase an item however.

![Image](https://github.com/user-attachments/assets/a3aec1da-ff73-4360-b44d-bf6d59de110a)

**Comment by DovJacobson** [comment]
i think i have finally identifed the bug in ios26 and coded around it
it should work now -- if not i give up!!

**Comment by DovJacobson** [comment]
@jcorack2 @tawfik-azzabi please confirmn fix or not before closing

**Comment by tawfik-azzabi** [comment]
@DovJacobson I started testing the background inversion fix for left-handed users on v302.

I noticed that when creating or editing a player profile and selecting left-handed, the selection does not persist. After validation/saving, the setting automatically switches back to right-handed.

This behavior is occurring consistently across all tested platforms.

Can you please confirm if this is expected or if the handedness value might not be saving correctly?

**Comment by DovJacobson** [comment]
@tawfik --thank you for this note
this is absolutely NOT the desired behavior
s it true only of handedness or other features as well???

**Comment by DovJacobson** [comment]
gender -- for example might be similarly sensitive  -- but how about name, birthday, etc?

**Comment by tawfik-azzabi** [comment]
Only handedness value is reset to "right" everytime, the other values (inclufing contact info) are saved correctly.
As a consequence, the shop background is no more flipped but I don't think this is what the fix was about.

**Comment by DovJacobson** [comment]
@tawfik-azzabi thank you -- but my investigation seeems to reveal something slightly different.


It seem there are two different problems.
These may stem from a recent change in the data format. 
It was switched from machine-friendly numeric code ("-1") to human-friendly string ("left")

i am now working on these two problems


## 1 

the profile editor  shows that Lefty is right-handed even though the data shows that he is left handed

<img width="583" height="922" alt="Image" src="https://github.com/user-attachments/assets/67154ca5-7a8a-4674-adaa-c390e8a4d68d" />


<img width="1176" height="915" alt="Image" src="https://github.com/user-attachments/assets/1884ac00-4ee1-4bad-9364-0d8833874ac7" />




## 2

The photo of "Lefty" is correct in the profile editor

<img width="452" height="668" alt="Image" src="https://github.com/user-attachments/assets/857954e9-caa3-4fc3-b90b-8c2f5d0c81fa" />

but the photo is reversed in ordinary display.

<img width="802" height="810" alt="Image" src="https://github.com/user-attachments/assets/7bb85dca-f09e-47cc-961e-42b3d9424ac1" />

**Comment by DovJacobson** [comment]
--- working on it-- a lot of code still uses the old format & I need an hour or so

**Comment by tawfik-azzabi** [comment]
Ok I'll jump on tests as soon as it's fixed 
Thanks

**Comment by DovJacobson** [comment]
@tawfik-azzabi sorry for long delay
the editor now shows lefty/righty correctly
and i now notice that *all* avatar pictures are right/left reversed compared to inside profile editor
this means they are "camera" format not "mirror" format, but i do not feel one is right and one is wrong. Maybe better if they were perfectly consistent, but I do NOT consider this a trackable issue at all.


please test the two bugs mentioned in this thread

original issue: price tag flipping 
newer bug:  did not appear to retain "lefty" setting


then please follow through on testing the personalization suite!!

**Comment by tawfik-azzabi** [comment]
@DovJacobson Quick update before I proceed with the full personalization test suite.

- The left/right value is now correctly saved and applied.
- The hand positioning during gameplay matches the profile setting correctly.
- Howver, the avatar/profile picture appears reversed between the profile editor and the home screen.

Observations : The original issue (price tag flipping) is still present in iOS (but NOT in windows)

I’ll now continue with the 8 personalization tests and will report back once completed.

**Comment by DovJacobson** [comment]
very frustrating as i am now using completely different positioning technique.
(same technique on ios/windows/android

are all four statements below tested & true?
1. ios + righty = good
2. ios + lefty = bad
3. win + righty= good
4. win + lefty = good

**Comment by tawfik-azzabi** [comment]
All statements are correct except 3 (win + right = bad) - I missed it my bad !
Windows and ios are in opposite logics, even the shop background is flipped windows vs. ios

Below is a screen shot for every statment 

1. ios + righty = good 
<img width="2806" height="1298" alt="Image" src="https://github.com/user-attachments/assets/8e2a72e5-5c62-4580-95b5-d0b0de9e50c6" />

2. ios + lefty = bad 
<img width="2807" height="1302" alt="Image" src="https://github.com/user-attachments/assets/e79fd913-d241-4f87-ac4a-40f883406b47" />

3. win + righty = BAD (not good)
<img width="1445" height="950" alt="Image" src="https://github.com/user-attachments/assets/4918c13f-a8cd-4085-9ed7-7439dca14b8f" />

4. win + lefty = good
<img width="1451" height="941" alt="Image" src="https://github.com/user-attachments/assets/2690b71b-7da1-45eb-a542-0794c7e7f0bc" />
