### ISSUE TITLE
App blocked on home screen with persistent "rotate screen" message [iPhone]

### ISSUE THREAD

**Issue by tawfik-azzabi** [GamesThatWork/BrushUpBuilds#121]
Description :
When opening the app on iphone, it remains stuck on the home screen (profiles not displayed).
A message appears asking to rotate the screen horizontally, but even after rotating the device, the message stays visible, making it impossible to access the game.
demo in the video attached below : 
https://drive.google.com/file/d/1aYRMjO8ij5lueFsNVZeFLZGKdRIXczZ1/view?usp=sharing

To Reproduce
- Launch app on build v1.3.63 on iPhone
- Wait for home screen to load
- Message appears inviting to rotate screen horizontally
- Rotate device → message remains stuck

Expected behavior
After rotating the device, the message should disappear and the profiles/home screen should display normally, allowing access to the game.

Device(s) tested:
iphone 

Status: Blocking – prevents game access.

**Comment by DovJacobson** [comment]
Can you look at console messages with devtools/web inspector?

**Comment by tawfik-azzabi** [comment]
Hi, sorry for the delay ! 
Since I'm testing on iphone, a Mac is required to capture console logs is through Safari Web Inspector. I'm currently working from a Surface/Windows.
Find attached an updated video recorded few minutes ago : 
https://drive.google.com/file/d/1OYU8ItraOTwnaehMNftxDVSshtfM2Xx1/view?usp=sharing

**Comment by DovJacobson** [comment]
good video help
sorry for delay 
i think now fixed in 1.3.64

**Comment by tawfik-azzabi** [comment]
The issue is still reproductible on IPHONE ONLY (all good on iPad, android and Windows) with build v1.3.64 : 
Find attached an updated video recorded todayon iphone :
https://drive.google.com/file/d/1MkMiihfIV-i7qsRCV3TuQxhidYW212QQ/view?usp=sharing

Note : I still don't have autorisations to add or retrieve Labels.

**Comment by DovJacobson** [comment]
`Note : I still don't have autorisations to add or retrieve Labels.`


it seems to be you are overlooking an invitation

<img width="2052" height="1012" alt="Image" src="https://github.com/user-attachments/assets/93ff1d4c-ed3f-4d22-8e65-d6b8ce62ec0c" />

**Comment by DovJacobson** [comment]
please try 1.3.65 for this bug and the 'upside down' bug 
( 121 & 118 )

**Comment by tawfik-azzabi** [comment]
Tried on v1.3.69, issue with the home page :

iPhone : 
https://drive.google.com/file/d/1dPkydIzq2cvIv0cPywYp_Elcy2pQ5YPJ/view?usp=drivesdk

iPad : 
https://drive.google.com/file/d/1XtxRYUvbTCkNlZQRMATfemvj-ylPAWpG/view?usp=drivesdk

**Comment by tawfik-azzabi** [comment]
Tested on v1.3.70, 

- iPad : problem fixed
- iPhone: still have the same issue (see video below) : 

https://drive.google.com/file/d/1jXor33g5EXXJQvvM0ZFo_u5WeAGnGs8n/view?usp=sharing

**Comment by DovJacobson** [comment]
@tawfik-azzabi 
to be clear: this bug is only on iPhone held 180⁰ inverted portrait?
or also 0⁰ normal portrait?

**Comment by tawfik-azzabi** [comment]
Both, you can see the moment I turn the iPhone on the video, first the iphone is held verticaly then I turn it 180° : 

The first seconds of the video the iPhone is held 0° normal portrait (vertical) showing the follwing :
<img width="628" height="1356" alt="Image" src="https://github.com/user-attachments/assets/6af3e5f0-5997-49ce-b433-9d86eff7b315" />

Then the iphone is held 180° displays the follwing : 
<img width="628" height="1363" alt="Image" src="https://github.com/user-attachments/assets/9dd0931e-5e83-4520-b16b-419cba6ed83c" />

**Comment by DovJacobson** [comment]
i am a little bit confused

PORTRAIT NORMAL
The image you show for the ⁰0 case looks correct. 
It is supposed to display that until you rotate it to landscape orientation.
If you do nothing, after a while it will print a clue on the screen

Is it not showing the clue?
is it not moving forward when you rotate it to landscape?


POTRAIT INVERTED
Wow messed up!! what happens if you rotate it  90⁰ ?  -90⁰  ???

**Comment by tawfik-azzabi** [comment]
I agree it's confusing, let me show you a video when I recorded my self handling the phone, it's more clear : 
https://drive.google.com/file/d/1IhNeFGId-8KyUsjfd-bhIHcTjW6Y5Idi/view?usp=sharing

**Comment by DovJacobson** [comment]
Thank you Tawfik... this video helps a lot -- but it is terrifying!!

Here's what I see on iPhone 16 ios 18 

1: PORTRAIT MODE

<img width="893" height="1677" alt="Image" src="https://github.com/user-attachments/assets/6c08a2e5-2096-4ddd-a15b-6220180b1463" />

2: ROTATE DEVICE

<img width="1778" height="1032" alt="Image" src="https://github.com/user-attachments/assets/c1def638-4a7b-41ee-a598-02bafbab3dc5" />


what hardware / os are you using?

**Comment by tawfik-azzabi** [comment]
I’m using iPhone 14 Pro / iOS 26.0 (the latest)

**Comment by DovJacobson** [comment]
same (good) behavior on iPhone 12 mini / ios 17
 ios 14 is bad

**Comment by DovJacobson** [comment]
As of 1.3.110 this has been fixed, in a heavy handed way.
In portrait mode, ios26 no longer urges the player to rotate his screen. 
It is now playable in landscape or (very unpleasantly) portrait orientation.

**Comment by tawfik-azzabi** [comment]
Checked on iPhone 1.3.110. The issue is solved ! 

<img width="1278" height="590" alt="Image" src="https://github.com/user-attachments/assets/91076baf-7fd4-48e2-a653-2c80e3021441" />

<img width="590" height="1278" alt="Image" src="https://github.com/user-attachments/assets/aafaf41b-ee51-4e2d-9cc2-85ae7f7f9897" />
