### ISSUE TITLE
BRUSHUP : Windows authentication – Successful login but stuck on authentication screen

### ISSUE THREAD

**Issue by tawfik-azzabi** [GamesThatWork/BrushUpBuilds#139]
When using the Windows authentication option, the authentication process completes successfully (Microsoft account login confirmed), but the app does not redirect to the main screen.

<img width="1440" height="911" alt="Image" src="https://github.com/user-attachments/assets/2846e284-3606-465b-ac5e-6787fe4510fd" />

**Comment by DovJacobson** [comment]
I cannot duplicate. (not even the "en cours" screen or similar)
I assume that you have a valiud Microsoft account?  and this is Windows 11?

Please send any console messages, especially ERROR
Thanks

**Comment by tawfik-azzabi** [comment]
Yes I have a valid Microsoft account and I'm working on Windows 11 (Surface Pro9)

Find attached the console log and below a screenshot of console errors :

[play.brushupgame.com-1762207144024.log](https://github.com/user-attachments/files/23318790/play.brushupgame.com-1762207144024.log)

<img width="2880" height="776" alt="Image" src="https://github.com/user-attachments/assets/cb844336-d2e8-4a15-83aa-ecc23610652b" />

I also recorded a video while reproducing the issue : 
https://drive.google.com/file/d/187LyCB5X4KRmYBhMC67MyCX0PDWQ3qOX/view?usp=sharing

**Comment by DovJacobson** [comment]
@tawfik-azzabi  please retest now... 
but MICROSOFT is not an approved authenticator for this project - so very low priority

**Comment by DovJacobson** [comment]
version 1.5.179+
and sign on as a tester eg: XC555 or whatever

**Comment by DovJacobson** [comment]
oops maybe 1.5.181

**Comment by tawfik-azzabi** [comment]
@DovJacobson 
I attempted to retest the issue, but I’m currently blocked at the home screen on all platforms, the game does not progress beyond the landing page

<img width="1773" height="1028" alt="Image" src="https://github.com/user-attachments/assets/a34e81de-1490-4223-bdb0-9d6afb50e8c2" />

May be due to a rollout in progress ?

**Comment by DovJacobson** [comment]
yes- a bug introduced late at night
-- but I fell asleep before discovering it.

now fixed,, please retry.

**Comment by tawfik-azzabi** [comment]
Yes problem fixed ! 
I'm resuming tests now

**Comment by jcorack2** [comment]
@tawfik-azzabi - It looks like the original issue presented in this thread has been resolved, is that correct? If so, please close this issue when you get a moment. Thanks!

**Comment by tawfik-azzabi** [comment]
@jcorack2 thanks for the reminder, the Microsoft authentification is still not working.
When using the Windows authentication option, the authentication process completes successfully (Microsoft account login confirmed), but the app does not redirect to the main screen.

**Comment by jcorack2** [comment]
Thanks for clarifying Tawfik. I removed the please close tag and this issue will remain open, but as Dov pointed out we are only using phone sign-in for the current study so this is not a high priority issue at the moment.

**Comment by DovJacobson** [comment]
Close or remove the` UH3 `label from this issue so it does not appear in` OPEN UH3 ISSUES `report

**Comment by DovJacobson** [comment]
@jcorack2  
please close this bug 
months ago, the UW team declined my offer to use your Azure (Microsoft)-based UW organizational sign on. It is way too late now. Please close.
