### ISSUE TITLE
BRUSHUP :: Impossible to log out / Auto re-login prevents testing authentication flows

### ISSUE THREAD

**Issue by tawfik-azzabi** [GamesThatWork/BrushUpBuilds#166]
Environment
- Build: v1.5.139
- URLs tested: https://play.brushupgame.com/XCT222

Platforms:

- Surface Pro – Windows 11
- Galacy TabA - Android
- iPhone 15 – iOS 26

Description
Once a user is authenticated (via Google in this case), there is no way to log out of the application.
When attempting to disconnect in order to re-test authentication flows, the app automatically re-authenticates the user using the existing Google session.

Steps to Reproduce
- Log in using Google authentication.
- Navigate to settings / attempt to log out (if available).
- Close and relaunch the app.
- Observe the authentication behavior.

Expected Result
- The user (or tester) should be able to:
- log out explicitly, or
- disable auto-login temporarily, or
- access the authentication screen again to select another method.

**Comment by DovJacobson** [comment]
@tawfik-azzabi please explain
1: what is the difference between issue https://github.com/GamesThatWork/BrushUpBuilds/issues/166 & https://github.com/GamesThatWork/BrushUpBuilds/issues/167?


see 167

**Comment by tawfik-azzabi** [comment]
@DovJacobson 
Here is a clarification of the two recently reported issues related to logout behavior:

#166 – BrushUp (Logout button ineffective)
In BrushUp, a “Sign Out” button is present, but it does not work as expected.
When the user taps “Sign Out”, the application automatically signs back, without returning to the authentication screen.
As a result, the user cannot effectively log out or switch authentication method.

#167 – BrushDown (No logout mechanism at all)
In BrushDown, once authentication is completed, there is no logout option available in the app.
The user is permanently signed in, and the application always resumes using the existing session, making it impossible to log out or re-authenticate.

**Comment by DovJacobson** [comment]
1  it still seems like these are reporting the same problem
and
2: I believe I have corrected this problem anyawqy now

**Comment by tawfik-azzabi** [comment]
Actually I'm still facing the same issue in v1.5.139 at least in iphone15 (IOS26) and Windows 11.
It's impossible to log out (using the button) and get back to re-authentification page
May be I should unistall the app and reinstall it again to check ?

**Comment by DovJacobson** [comment]
let me examine this again

**Comment by DovJacobson** [comment]
please tyry again in 1.5.140

**Comment by DovJacobson** [comment]
also i now understand how 166 and 167 are different

**Comment by tawfik-azzabi** [comment]
Issue solved in v1.5.142 (in all platforms)
